// CONFIGURACIÓN — Supabase

const SUPABASE_URL = 'https://aiaynpttrpxuymvabdij.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpYXlucHR0cnB4dXltdmFiZGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NTA4NTMsImV4cCI6MjA5MzIyNjg1M30.LDMxQ3OIGZmmJ8Gx-rncsxZZpLL0rQwPhKUjDzOPOjE';